"""
KitInspect Report Generator
Generates structured JSON/text reports from scan results.
"""

import json
import sys
import os
import argparse
from datetime import datetime
from pathlib import Path


SEVERITY_ORDER = {'critical': 0, 'high': 1, 'medium': 2, 'low': 3, 'info': 4}
SEVERITY_ICONS = {
    'critical': '🔴', 'high': '🟠', 'medium': '🟡',
    'low': '🔵', 'info': '⚪'
}
RISK_COLORS = {
    'critical': '\033[1;91m', 'high': '\033[91m',
    'medium': '\033[93m', 'low': '\033[92m', 'unknown': '\033[97m'
}
RESET = '\033[0m'


def load_result(path: str) -> dict:
    with open(path) as f:
        return json.load(f)


def build_executive_summary(result: dict) -> dict:
    findings = result.get('Findings', [])
    score = result.get('Score', {})

    severity_counts = {'critical': 0, 'high': 0, 'medium': 0, 'low': 0, 'info': 0}
    for f in findings:
        sev = f.get('Severity', 'info').lower()
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    dangerous_perms = [p for p in result.get('Permissions', []) if p.get('Dangerous')]
    iocs = result.get('IOCs', [])

    return {
        'generated_at': datetime.utcnow().isoformat() + 'Z',
        'tool': 'KitInspect v1.0.0',
        'target': result.get('Meta', {}).get('FileName', 'unknown'),
        'package': result.get('Meta', {}).get('PackageName', 'unknown'),
        'risk_level': score.get('RiskLevel', 'unknown'),
        'risk_score': score.get('Overall', 0),
        'total_findings': len(findings),
        'findings_by_severity': severity_counts,
        'dangerous_permissions': len(dangerous_perms),
        'total_iocs': len(iocs),
        'top_findings': sorted(findings, key=lambda f: SEVERITY_ORDER.get(f.get('Severity', 'info').lower(), 99))[:5],
        'disclaimer': 'Generated by KitInspect for defensive security analysis. For authorized use only.',
    }


def generate_text_report(result: dict) -> str:
    lines = []
    sep = '─' * 70

    def line(s=''):
        lines.append(s)

    def section(title):
        line()
        line(f'  ┌─ {title} {sep[len(title)+5:]}')

    def row(k, v, indent=4):
        lines.append(f"  │{' ' * indent}{k:<26}{v}")

    def end():
        line(f'  └{sep}')
    line()
    line('  ╔══════════════════════════════════════════════════════════════╗')
    line('  ║              KITINSPECT SECURITY ANALYSIS REPORT            ║')
    line('  ╚══════════════════════════════════════════════════════════════╝')
    line(f"  Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}")
    line()

    meta = result.get('Meta', {})
    score = result.get('Score', {})
    risk = score.get('RiskLevel', 'unknown')
    risk_score = score.get('Overall', 0)

    section('FILE METADATA')
    row('File:', meta.get('FileName', '—'))
    row('Package:', meta.get('PackageName', '—'))
    row('MD5:', meta.get('MD5', '—'))
    row('SHA256:', meta.get('SHA256', '—'))
    row('File Size:', f"{meta.get('FileSize', 0):,} bytes")
    row('Activities:', str(len(meta.get('Activities', []))))
    row('Services:', str(len(meta.get('Services', []))))
    row('Native Libs:', ', '.join(meta.get('NativeLibs', [])) or '—')
    end()
    section('RISK SCORE')
    bar_width = 40
    filled = int(risk_score / 100 * bar_width)
    bar = '█' * filled + '░' * (bar_width - filled)
    row('Score:', f"{risk_score:.1f}/100  [{risk.upper()} RISK]")
    row('Visual:', f"|{bar}|")
    bd = score.get('Breakdown', {})
    for k, v in bd.items():
        row(f'  {k.title()}:', f"{v:.1f} pts")
    end()
    perms = result.get('Permissions', [])
    dangerous = [p for p in perms if p.get('Dangerous')]
    section(f'PERMISSIONS ({len(perms)} total, {len(dangerous)} dangerous)')
    if dangerous:
        line('  │    ▸ DANGEROUS:')
        for p in dangerous:
            short = p['Name'].split('.')[-1]
            desc = p.get('Description', '')
            line(f"  │      ⬥ {short:<40} {desc}")
    normal = [p for p in perms if not p.get('Dangerous')]
    if normal:
        line(f"  │    ▸ Normal permissions: {len(normal)}")
    end()
    findings = sorted(
        result.get('Findings', []),
        key=lambda f: SEVERITY_ORDER.get(f.get('Severity', 'info').lower(), 99)
    )
    section(f'SECURITY FINDINGS ({len(findings)})')
    if not findings:
        line('  │    ✔  No security findings')
    for i, f in enumerate(findings):
        if i > 0:
            line('  │    · · ·')
        sev = f.get('Severity', 'info')
        icon = SEVERITY_ICONS.get(sev, '·')
        cwe = f' [{f["CWE"]}]' if f.get('CWE') else ''
        line(f"  │    {icon} [{sev.upper():<8}] {f.get('ID','')}  {f.get('Title','')}{cwe}")
        desc = f.get('Description', '')
        words, cur_line = desc.split(), []
        for w in words:
            if sum(len(x)+1 for x in cur_line) + len(w) > 60:
                line(f"  │             {' '.join(cur_line)}")
                cur_line = [w]
            else:
                cur_line.append(w)
        if cur_line:
            line(f"  │             {' '.join(cur_line)}")
        if f.get('Remediation'):
            line(f"  │      Fix: {f['Remediation'][:80]}")
    end()
    iocs = result.get('IOCs', [])
    section(f'INDICATORS OF COMPROMISE ({len(iocs)})')
    if not iocs:
        line('  │    No IOCs detected')
    else:
        by_type = {}
        for ioc in iocs:
            t = ioc.get('Type', 'unknown')
            by_type.setdefault(t, []).append(ioc)
        for t, items in by_type.items():
            line(f"  │    ▸ {t.upper()}s ({len(items)}):")
            for ioc in items[:5]:
                val = ioc.get('Value', '')[:60]
                sev = ioc.get('Severity', 'info')
                line(f"  │      [{sev.upper():<8}] {val}")
            if len(items) > 5:
                line(f"  │      ... and {len(items)-5} more")
    end()
    strs = result.get('Strings', {})
    section('STRING ANALYSIS')
    row('Total Strings:', str(strs.get('Total', 0)))
    row('Embedded URLs:', str(len(strs.get('URLs', []))))
    row('IP Addresses:', str(len(strs.get('IPs', []))))
    row('API Endpoints:', str(len(strs.get('Endpoints', []))))
    row('Suspicious Patterns:', str(len(strs.get('Secrets', []))))
    end()
    line()
    line('  ─────────────────────────────────────────────────────────────────')
    line('  KitInspect · Defensive Security Analysis · For authorized use only')
    line()

    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description='KitInspect Report Generator')
    parser.add_argument('result_file', help='Path to KitInspect JSON result file')
    parser.add_argument('--format', choices=['text', 'json', 'summary'], default='text')
    parser.add_argument('--output', help='Output file (default: stdout)')
    args = parser.parse_args()

    if not os.path.exists(args.result_file):
        print(json.dumps({'error': f'Result file not found: {args.result_file}'}))
        sys.exit(1)

    result = load_result(args.result_file)

    if args.format == 'text':
        output = generate_text_report(result)
    elif args.format == 'summary':
        output = json.dumps(build_executive_summary(result), indent=2)
    else:
        output = json.dumps(result, indent=2)

    if args.output:
        Path(args.output).parent.mkdir(parents=True, exist_ok=True)
        with open(args.output, 'w') as f:
            f.write(output)
        print(f"Report saved to: {args.output}")
    else:
        print(output)


if __name__ == '__main__':
    main()
